bremersee:
  ldaptive:
    ldaptive-template-class: org.bremersee.ldaptive.LdaptiveSambaTemplate
    immutable: true
    use-start-tls: false
    # BREMERSEE_LDAPTIVE_BIND_DN
    bind-dn: "Administrator"
    # BREMERSEE_LDAPTIVE_BIND_CREDENTIALS
    bind-credentials: ""
    # BREMERSEE_LDAPTIVE_POOLED
    pooled: false
    connection-validator:
      search-request:
        base-dn: ${bremersee.dc.base-dn}
    connection-pool:
      min-pool-size: 3
      max-pool-size: 10
      validate-on-check-in: false
      validate-on-check-out: false
      validate-periodically: true
      validator:
        search-request:
          base-dn: ${bremersee.dc.base-dn}
  authentication:
    remember-me:
      # BREMERSEE_AUTHENTICATION_REMEMBER_ME_KEY
      key: ${LDAP_REMEMBER_ME:${spring.application.name}}
    ldaptive:
      template: active_directory
      user-base-dn: ${bremersee.dc.base-dn}
      user-find-one-search-scope: subtree
      role-prefix: "ROLE_"
      role-case-transformation: to_upper_case
      role-string-replacements:
        - regex: "[- ]"
          replacement: "_"
        - regex: "_ADMINS"
          replacement: "_ADMIN"
      default-roles:
        - "ROLE_LOCAL_USER"
      role-mapping:
        - source: "Domain Admins"
          target: "ROLE_ADMIN"
        - source: "samba-admins"
          target: "ROLE_ADMIN"
  dc:
    # BREMERSEE_DC_BASE_DN
    base-dn: ""
    company-name: "Samba AD DC Manager"
    company-url: "#"
    # BREMERSEE_DC_CRYPTO_SECRET
    crypto-secret: "change-it"
    cli:
      hostname-binary: /usr/bin/hostname
      samba-tool-binary: /usr/bin/samba-tool
      samba-tool-credentials-options: "-UAdministrator --password='${bremersee.ldaptive.bind-credentials}'"
      dhcp-lease-list-binary: /usr/sbin/dhcp-lease-list
      sudo:
        using-sudo: false
      ssh:
        using-ssh: false
    domain:
      forbidden-new-sam-account-names:
        - "root"
        - "admin"
        - "guest"
    user:
      user-able-to-change-email: true
      default-language: "de-DE"
      default-login-page:
        url: ""
        name: ""
        using-netbios-domain-prefix: false

  exception-mapping:
    api-paths:
      - /api/**
    default-exception-mapping-config:
      include-message: true
      include-exception: true
      include-application-name: true
      include-path: true
      include-handler: true
      include-stack-trace: true
      include-cause: true

  comparator:
    converter:
      argument-separator: ","
      chain-separator: ";"

eureka:
  client:
    enabled: false

spring:
  profiles:
    default: mock
  application:
    name: samba-ad-dc-manager
  messages:
    use-code-as-default-message: true
    fallback-to-system-locale: false
  cache:
    jcache:
      config: classpath:ehcache.xml
  cloud:
    config:
      enabled: false
      uri:
      username:
      password:
      fail-fast: true
      retry:
        initial-interval: 3000
        max-interval: 4000
        max-attempts: 8
        multiplier: 1.1

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: when_authorized
  health:
    mail:
      enabled: false

server:
  port: 8080

logging:
  level:
    ROOT: info
    com.netflix.eureka.registry: warn
    com.netflix.discovery.shared.resolver: warn
    org.bremersee: info
    org.springframework.cloud.configclient: warn

---

spring:
  config:
    activate:
      on-profile: mock

bremersee:
  dc:
    base-dn: dc=samdom,dc=example,dc=org

---

spring:
  config:
    activate:
      on-profile: local

bremersee:
  ldaptive:
    ldap-url: ldaps://localhost:636
    ssl-config:
      trust-certificates: "/var/lib/samba/private/tls/ca.pem,/var/lib/samba/private/tls/cert.pem"
  dc:
    cli:
      sudo:
        using-sudo: true
        sudo-command: /usr/bin/sudo
      ssh:
        using-ssh: false

---

spring:
  config:
    activate:
      on-profile: remote

bremersee:
  ldaptive:
    # BREMERSEE_LDAPTIVE_LDAP_URL
    ldap-url: ldaps://localhost:636
  dc:
    cli:
      sudo:
        using-sudo: false
      ssh:
        using-ssh: true
        ssh-command: /usr/bin/ssh root@${bremersee.dc.domain.host-name:}
    domain:
      # BREMERSEE_DC_DOMAIN_HOST_NAME
      host-name: "localhost"

---

spring:
  config:
    activate:
      on-profile: mail
  mail:
    # SPRING_MAIL_HOST
    host: smtp.mail.me.com
    # SPRING_MAIL_PORT
    port: 587
    test-connection: true
    properties:
      mail.smtp.starttls.enable: true
    # SPRING_MAIL_USERNAME
    # SPRING_MAIL_PASSWORD
bremersee:
  dc:
    email:
      # BREMERSEE_DC_EMAIL_SENDER
      sender: ""
      base-uri: "http://localhost:8080"

---

spring:
  config:
    activate:
      on-profile: jwt
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.bremersee.org/realms/eixe/protocol/openid-connect/certs
bremersee:
  authentication:
    jwt-converter:
      name-json-path: $.preferred_username
      first-name-json-path: $.given_name
      last-name-json-path: $.family_name
      roles-json-path: $.realm_access.roles
      roles-value-list: true
      role-prefix: "ROLE_"
      role-case-transformation: to_upper_case
      role-string-replacements:
        - regex: "[- ]"
          replacement: "_"
        - regex: "_ADMINS"
          replacement: "_ADMIN"
      default-roles:
        - "ROLE_LOCAL_USER"
      role-mapping:
        - source: "Domain Admins"
          target: "ROLE_ADMIN"
        - source: "samba-admins"
          target: "ROLE_ADMIN"

---

spring:
  config:
    activate:
      on-profile: debian

logging:
  file:
    name: /var/log/samba-ad-dc-manager/samba-ad-dc-manager.log
  logback:
    rollingpolicy:
      max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/samba-ad-dc-manager
      prefix: access_log
