#!/usr/bin/env bash

DEBIAN_NAME="samba-ad-dc-manager"
APP_NAME=$DEBIAN_NAME
USER_NAME="smb-mngr"
GROUP_NAME=$USER_NAME
SUDO_FILE=/etc/sudoers.d/$DEBIAN_NAME
SUDO_ENTRY="$USER_NAME ALL = NOPASSWD: /usr/bin/hostname, /usr/bin/samba-tool, /usr/sbin/dhcp-lease-list"

if ! /usr/bin/getent passwd $USER_NAME
then
  /usr/sbin/adduser --system --home /var/lib/$DEBIAN_NAME --shell /bin/false --no-create-home --group --disabled-login $USER_NAME
fi

/bin/mkdir -p /var/lib/$DEBIAN_NAME
/bin/chown -R $USER_NAME:$GROUP_NAME /var/lib/$DEBIAN_NAME
/bin/chmod 750 /var/lib/$DEBIAN_NAME

/bin/mkdir -p /var/log/$DEBIAN_NAME
/bin/chown -R $USER_NAME:$GROUP_NAME /var/log/$DEBIAN_NAME
/bin/chmod 750 /var/log/$DEBIAN_NAME

if [ ! -e $SUDO_FILE ]; then
  touch "$SUDO_FILE"
fi
grep -q "$SUDO_ENTRY" "$SUDO_FILE"
if [ $? -eq 1 ]; then
  echo -e "$SUDO_ENTRY" >> "$SUDO_FILE"
fi

/bin/systemctl enable $DEBIAN_NAME.service
if [ -e /var/lib/$DEBIAN_NAME/$APP_NAME.conf.user ] && [ -e /var/lib/$DEBIAN_NAME/application.yml.user ]; then
  if [ -e /var/lib/$DEBIAN_NAME/$APP_NAME.conf.user ]; then
    cp /var/lib/$DEBIAN_NAME/$APP_NAME.conf /var/lib/$DEBIAN_NAME/$APP_NAME.conf.package
    cp /var/lib/$DEBIAN_NAME/$APP_NAME.conf.user /var/lib/$DEBIAN_NAME/$APP_NAME.conf
    rm -f /var/lib/$DEBIAN_NAME/$APP_NAME.conf.user
  fi
  if [ -e /var/lib/$DEBIAN_NAME/application.yml.user ]; then
    cp /var/lib/$DEBIAN_NAME/application.yml /var/lib/$DEBIAN_NAME/application.yml.package
    cp /var/lib/$DEBIAN_NAME/application.yml.user /var/lib/$DEBIAN_NAME/application.yml
    rm -f /var/lib/$DEBIAN_NAME/application.yml.user
  fi
fi

/bin/systemctl start $DEBIAN_NAME.service

exit 0