#!/usr/bin/env bash

SUDO_FILE=/etc/sudoers
SUDO_ENTRY="dc-con ALL = NOPASSWD: /usr/bin/samba-tool, /usr/bin/kinit, /usr/sbin/dhcp-lease-list"

/usr/bin/getent passwd dc-con
if [ ! $? -eq 0 ]; then
  /usr/sbin/adduser --system --home /var/lib/dc-con --shell /bin/false --no-create-home --group --disabled-login dc-con
fi

/bin/mkdir -p /var/lib/dc-con
/bin/chown -R dc-con:dc-con /var/lib/dc-con
/bin/chmod -R u+rwx /var/lib/dc-con

/bin/mkdir -p /var/log/dc-con
/bin/chown -R dc-con:dc-con /var/log/dc-con
/bin/chmod u+rwx /var/log/dc-con

if [ ! -e /etc/systemd/system/dc-con.service ]; then
  ln -s /lib/systemd/system/dc-con.service /etc/systemd/system/dc-con.service
fi

grep -q "$SUDO_ENTRY" "$SUDO_FILE"
if [ $? -eq 1 ]; then
  echo -e "$SUDO_ENTRY" >> "$SUDO_FILE"
fi

/bin/systemctl enable dc-con.service
if [ -e /var/lib/dc-con/dc-con.conf.user ]; then
    cp /var/lib/dc-con/dc-con.conf /var/lib/dc-con/dc-con.conf.package
    cp /var/lib/dc-con/dc-con.conf.user /var/lib/dc-con/dc-con.conf
    rm -f /var/lib/dc-con/dc-con.conf.user
    /bin/systemctl start dc-con.service
fi

exit 0