#!/bin/bash

if [ -e /etc/systemd/system/dc-con.service ]; then
    /bin/systemctl stop dc-con.service
    /bin/systemctl disable dc-con.service
fi

if [ -e /var/lib/dc-con/dc-con.conf ]; then
    cp /var/lib/dc-con/dc-con.conf /var/lib/dc-con/dc-con.conf.user
fi

exit 0