JAVA_OPTS="-Xmx512m -Djava.security.egd=file:/dev/./urandom"
RUN_ARGS="--spring.profiles.active=debian,mock --spring.config.location=/var/lib/samba-ad-dc-manager/application.yml"
# RUN_ARGS="--spring.profiles.active=debian,local --spring.config.location=/var/lib/samba-ad-dc-manager/application.yml"
# RUN_ARGS="--spring.profiles.active=debian,local,mail --spring.config.location=/var/lib/samba-ad-dc-manager/application.yml"
